/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;


import java.awt.Color;
import java.awt.Font;
import java.sql.SQLException;

import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;

import modelo.Alojamiento;


/**
 *
 * @author Santiago Parra
 */
public class frmRegistrarAlojamiento5 extends javax.swing.JFrame {

    /**
     * Creates new form frmRegistrarAlojamiento1
     */
    public static Alojamiento alojamiento = frmRegistrarAlojamiento3.alojamiento;

    public frmRegistrarAlojamiento5() {
        initComponents();
     
        

        this.getContentPane().setBackground(Color.white);
        Panel1.setBackground(Color.red);
        pn2.setBackground(Color.white);
        Font fuente = new Font("Comic Sans MS", 1, 12);
        pn2.setFont(fuente);
        this.getContentPane().setBackground(Color.white);
        this.setLocationRelativeTo(null);
        this.setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel9 = new javax.swing.JLabel();
        buttonGroup1 = new javax.swing.ButtonGroup();
        Panel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        btnSiguiente = new javax.swing.JButton();
        pn2 = new javax.swing.JPanel();
        chTomaCorrientes = new javax.swing.JCheckBox();
        chTelevisor = new javax.swing.JCheckBox();
        chSistemailuminacion = new javax.swing.JCheckBox();
        chMuebles = new javax.swing.JCheckBox();
        chSala = new javax.swing.JCheckBox();
        chTerraza = new javax.swing.JCheckBox();
        chJacuzzi = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();
        rbSi = new javax.swing.JRadioButton();
        rbNo = new javax.swing.JRadioButton();

        jLabel9.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        jLabel9.setText(" Presione aqui para cargar foto");
        jLabel9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel9MouseClicked(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Panel1.setForeground(new java.awt.Color(255, 0, 0));

        jLabel4.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Registrar Alojamiento");

        javax.swing.GroupLayout Panel1Layout = new javax.swing.GroupLayout(Panel1);
        Panel1.setLayout(Panel1Layout);
        Panel1Layout.setHorizontalGroup(
            Panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel1Layout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addComponent(jLabel4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        Panel1Layout.setVerticalGroup(
            Panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Panel1Layout.createSequentialGroup()
                .addContainerGap(29, Short.MAX_VALUE)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
        );

        btnSiguiente.setText("Siguiente");
        btnSiguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSiguienteActionPerformed(evt);
            }
        });

        pn2.setBorder(javax.swing.BorderFactory.createTitledBorder("Elija las Comodidades que tiene su alojamiento"));

        chTomaCorrientes.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        chTomaCorrientes.setText("Toma Corrientes");
        chTomaCorrientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chTomaCorrientesActionPerformed(evt);
            }
        });

        chTelevisor.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        chTelevisor.setText("Televisor");

        chSistemailuminacion.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        chSistemailuminacion.setText("Sistema de iluminacion");

        chMuebles.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        chMuebles.setText("Muebles");

        chSala.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        chSala.setText("Sala");

        chTerraza.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        chTerraza.setText("Terraza");
        chTerraza.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chTerrazaActionPerformed(evt);
            }
        });

        chJacuzzi.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        chJacuzzi.setText("Jacuzzi");
        chJacuzzi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chJacuzziActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pn2Layout = new javax.swing.GroupLayout(pn2);
        pn2.setLayout(pn2Layout);
        pn2Layout.setHorizontalGroup(
            pn2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn2Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(pn2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(chJacuzzi)
                    .addComponent(chSistemailuminacion)
                    .addComponent(chTomaCorrientes)
                    .addComponent(chTerraza)
                    .addComponent(chMuebles, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pn2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(chSala, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(chTelevisor, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(99, Short.MAX_VALUE))
        );
        pn2Layout.setVerticalGroup(
            pn2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(chTomaCorrientes)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chTelevisor)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chSistemailuminacion)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chMuebles)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chSala)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chTerraza)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chJacuzzi)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        jLabel1.setText("Tiene acceso para silla de ruedas");

        buttonGroup1.add(rbSi);
        rbSi.setText("Si");
        rbSi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbSiActionPerformed(evt);
            }
        });

        buttonGroup1.add(rbNo);
        rbNo.setText("No");
        rbNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbNoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Panel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pn2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(60, 60, 60)
                                .addComponent(btnSiguiente, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(136, 136, 136)
                        .addComponent(rbSi)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(rbNo))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(98, 98, 98)
                        .addComponent(jLabel1)))
                .addContainerGap(68, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Panel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(pn2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbSi)
                    .addComponent(rbNo))
                .addGap(18, 18, 18)
                .addComponent(btnSiguiente)
                .addContainerGap(48, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSiguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSiguienteActionPerformed
        try {
            ArrayList<String>comodidades = new ArrayList();
            if (chTomaCorrientes.isSelected()) {
                comodidades.add(chTomaCorrientes.getText());
            }
            if (chTelevisor.isSelected()) {
                comodidades.add(chTelevisor.getText());
            }
            if (chSistemailuminacion.isSelected()) {
                comodidades.add(chSistemailuminacion.getText());
            }
            if (chMuebles.isSelected()) {
                comodidades.add(chMuebles.getText());
            }
            if (chSala.isSelected()) {
                comodidades.add(chSala.getText());
            }
            if (chTerraza.isSelected()) {
                comodidades.add(chTerraza.getText());
            }   
            if (chJacuzzi.isSelected()) {
                comodidades.add(chJacuzzi.getText());
            }
            alojamiento.setListaComodidades(comodidades);
            if (rbNo.isSelected()) {
                alojamiento.setAccessibilidad("No");
            }else if(rbSi.isSelected()){
                alojamiento.setAccessibilidad("Si");
            }
            
            frmRegistrarAlojamiento6 vista = new frmRegistrarAlojamiento6();
            vista.setVisible(true);
            this.dispose();
        } catch (SQLException ex) {
            Logger.getLogger(frmRegistrarAlojamiento5.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnSiguienteActionPerformed

    private void jLabel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel9MouseClicked

    private void chTomaCorrientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chTomaCorrientesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chTomaCorrientesActionPerformed

    private void chTerrazaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chTerrazaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chTerrazaActionPerformed

    private void chJacuzziActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chJacuzziActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chJacuzziActionPerformed

    private void rbSiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbSiActionPerformed

       
    }//GEN-LAST:event_rbSiActionPerformed

    private void rbNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbNoActionPerformed
        
    }//GEN-LAST:event_rbNoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmRegistrarAlojamiento5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmRegistrarAlojamiento5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmRegistrarAlojamiento5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmRegistrarAlojamiento5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {

                new frmRegistrarAlojamiento5().setVisible(true);

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Panel1;
    private javax.swing.JButton btnSiguiente;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JCheckBox chJacuzzi;
    private javax.swing.JCheckBox chMuebles;
    private javax.swing.JCheckBox chSala;
    private javax.swing.JCheckBox chSistemailuminacion;
    private javax.swing.JCheckBox chTelevisor;
    private javax.swing.JCheckBox chTerraza;
    private javax.swing.JCheckBox chTomaCorrientes;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel pn2;
    private javax.swing.JRadioButton rbNo;
    private javax.swing.JRadioButton rbSi;
    // End of variables declaration//GEN-END:variables
}
